# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main  # Runs the pipeline when code is pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu machine

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      sudo apt update
      sudo apt install -y k6
    displayName: 'Install K6'  # Installing K6 on the machine

  - script: |
      k6 run loadTest.js
    displayName: 'Run Performance Test'  # Running the K6 test script

